// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"WedhaWS/utsgosmt5/alumni-tracer/db"
	"WedhaWS/utsgosmt5/alumni-tracer/helper"
	"WedhaWS/utsgosmt5/alumni-tracer/app/repository"
	"WedhaWS/utsgosmt5/alumni-tracer/app/services"
)

// Injectors from injector.go:

func InitializedService() *services.AppServices {
	alumniRepository := repository.NewAlumniRepository()
	sqlDB := db.NewDB()
	validate := helper.NewValidator()
	alumniService := services.NewAlumniService(alumniRepository, sqlDB, validate)
	pekerjaanAlumniRepository := repository.NewPekerjaanAlumniRepository()
	pekerjaanAlumniService := services.NewPekerjaanAlumniService(pekerjaanAlumniRepository, sqlDB, validate)
	userRepository := repository.NewUsersRepository()
	userService := services.NewUserService(userRepository, sqlDB, validate)
	appServices := services.NewAppService(alumniService, pekerjaanAlumniService, userService)
	return appServices
}
